service: gimme-time

provider:
  name: aws
  runtime: nodejs8.10
  environment:
  STAGE: ${opt:stage}

functions:
  gimmetime:
    handler: handler.helloFellows
    events:
      - http:
          path: /hi
          method: get
          request:
            parameters:
              querystrings:
                name: true
